export const enum Errors {
  EXISTENT_CARD = "EXISTENT_CARD",
  EXISTENT_CARD_GROUP = "EXISTENT_CARD_GROUP",
  UNEXISTENT_CARD = "UNEXISTENT_CARD",
  UNEXISTENT_CARD_GROUP = "UNEXISTENT_CARD_GROUP",
}
